### ISSUE TITLE
Is this addon still supported?

### ISSUE THREAD

**Issue by ghost** [joeyjumper94/Equestrian-Wastelanders-PPM#2]
Hello, I have some bugs with this addon, but I don't know if they will be fixed, because judging by the commit history, the last commit was 2 years ago and it seems to me that this addon is abandoned.

**Comment by joeyjumper94** [comment]
oh if there is a problem, can you report the bug with instructions on how you caused it?

**Comment by ghost** [comment]
So far I've noticed the following:
1)If another pony model with its own phong settings enters the player's field of vision, then the phong on the hands from CPPM starts to be applied from the pony from the player's field of view.
2)After the death of the player, after a few seconds, the corpse ragdoll "forgets" some settings, for example, my phong settings, wing model, wing color and cutiemark settings are reset.
3)The pony preset is sometimes not loaded after spawn, which is why sometimes have to call the "ppm_reload" command.
And can you please post your Discord username? And then I was once on your friends list, but due to problems with the old account, I had to delete it and now I can not reach you.

**Comment by joeyjumper94** [comment]
joey_#3699

**Comment by joeyjumper94** [comment]
1)If another pony model with its own phong settings enters the player's field of vision, then the phong on the hands from CPPM starts to be applied from the pony from the player's field of view. DONE
